### ISSUE TITLE
How do I close the connection after making a query and getting back results? 

### ISSUE THREAD

**Issue by Eithcowich** [ForbesLindesay/sync-mysql#9]
Also, is there a connection pool?

**Comment by ForbesLindesay** [comment]
https://github.com/ForbesLindesay/sync-mysql#connectiondispose

Yes there is a connection pool. It is limited to a single connection though because there is no point having multiple connections when your code is synchronous: https://github.com/ForbesLindesay/sync-mysql/blob/1a6c1aa3b589cb3f84a732d0555fe8f7239a9a98/src/worker.js#L7
